using DesignPatterns.AdapterPattern;
using DesignPatterns.CommandPattern;
using DesignPatterns.CompositePattern;
using DesignPatterns.DecoratorPattern;
using DesignPatterns.FactoryMethodPattern;
using DesignPatterns.ObserverPattern;
using DesignPatterns.Proxy_Pattern.Protection_Proxy;
using DesignPatterns.SingletonPattern;
using DesignPatterns.StatePattern;
using DesignPatterns.TemplateMethodPattern;

Console.WriteLine("Design Patterns in Action");
Console.WriteLine("Design Patterns: Adapter Pattern");
AdapterPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Command Pattern");
CommandPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Decorator Pattern");
DecoratorPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Composite Pattern");
CompositePatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Factory Method Pattern");
FactoryMethodPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Observer Pattern");
ObserverPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Singleton Pattern");
SingletonPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: State Pattern");
StatePatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Template Method Pattern");
TemplateMethodPatternTestDrive.test();
Console.WriteLine("-------------------------------");
Console.WriteLine("Design Patterns: Protection Proxy Pattern");
ProtectionProxyTestDrive.test();